# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du cours')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Identifiant')),
                ('category', models.CharField(choices=[('letters', 'Lettres'), ('numbers', 'Chiffres'), ('languages', 'Langues'), ('islamic', 'Éducation islamique'), ('science', 'Sciences'), ('art', 'Arts & créativité')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('age_min_months', models.PositiveIntegerField(default=24, verbose_name='Âge minimum (mois)')),
                ('age_max_months', models.PositiveIntegerField(default=72, verbose_name='Âge maximum (mois)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Image de couverture')),
                ('scene_url', models.URLField(blank=True, verbose_name='URL de la scène 3D')),
                ('is_3d', models.BooleanField(default=True, verbose_name='Contenu 3D')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ('category', 'order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre de la leçon')),
                ('content', models.TextField(blank=True, verbose_name='Contenu pédagogique')),
                ('media_url', models.URLField(blank=True, verbose_name='Média / vidéo')),
                ('duration_minutes', models.PositiveIntegerField(default=10, verbose_name='Durée (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ('course', 'order'),
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.PositiveIntegerField(default=0, verbose_name='Avancement (%)')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='children.child', verbose_name='Enfant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='education.course', verbose_name='Cours')),
                ('last_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.lesson', verbose_name='Dernière leçon')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'unique_together': {('child', 'course')},
            },
        ),
    ]
