# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='Groupe sanguin')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (cm)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Poids (kg)')),
                ('doctor_name', models.CharField(blank=True, max_length=120, verbose_name='Médecin référent')),
                ('doctor_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du médecin')),
                ('insurance_number', models.CharField(blank=True, max_length=80, verbose_name="Numéro d'assuré")),
                ('special_needs', models.TextField(blank=True, verbose_name='Besoins particuliers')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='children.child', verbose_name='Enfant')),
            ],
            options={
                'verbose_name': 'Dossier médical',
                'verbose_name_plural': 'Dossiers médicaux',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Maladie')),
                ('diagnosed_on', models.DateField(blank=True, null=True, verbose_name='Date de diagnostic')),
                ('is_chronic', models.BooleanField(default=False, verbose_name='Chronique')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='health.healthrecord', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Maladie',
                'verbose_name_plural': 'Maladies',
            },
        ),
        migrations.CreateModel(
            name='DietRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Restriction alimentaire')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_restrictions', to='health.healthrecord', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Restriction alimentaire',
                'verbose_name_plural': 'Restrictions alimentaires',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Allergène')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Modérée'), ('high', 'Élevée')], default='low', max_length=20, verbose_name='Gravité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='health.healthrecord', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Allergie',
                'verbose_name_plural': 'Allergies',
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Médicament')),
                ('dosage', models.CharField(blank=True, max_length=120, verbose_name='Posologie')),
                ('schedule', models.CharField(blank=True, max_length=120, verbose_name='Fréquence')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='health.healthrecord', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=150, verbose_name='Vaccin')),
                ('administered_on', models.DateField(verbose_name="Date d'administration")),
                ('next_dose_on', models.DateField(blank=True, null=True, verbose_name='Prochaine dose')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='health.healthrecord', verbose_name='Dossier médical')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
            },
        ),
    ]
