# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurseries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('boy', 'Garçon'), ('girl', 'Fille'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Genre')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='École / établissement')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enrolled_on', models.DateField(blank=True, null=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_children', to='nurseries.nursery', verbose_name='Crèche')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
