# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('info', 'Information'), ('health', 'Santé'), ('education', 'Éducation'), ('chat', 'Message'), ('approval', 'Validation de compte'), ('report', 'Rapport')], default='info', max_length=20, verbose_name='Catégorie')),
                ('title', models.CharField(max_length=180, verbose_name='Titre')),
                ('body', models.TextField(blank=True, verbose_name='Contenu')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Lien interne')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
            },
        ),
    ]
