# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('mood', models.CharField(choices=[('happy', 'Joyeux'), ('calm', 'Calme'), ('tired', 'Fatigué'), ('sad', 'Triste'), ('upset', 'Agité')], default='happy', max_length=20, verbose_name='Humeur')),
                ('appetite_score', models.PositiveSmallIntegerField(default=3, verbose_name='Appétit (1-5)')),
                ('sleep_minutes', models.PositiveIntegerField(default=0, verbose_name='Sommeil (minutes)')),
                ('behavior_score', models.PositiveSmallIntegerField(default=3, verbose_name='Comportement (1-5)')),
                ('learning_score', models.PositiveSmallIntegerField(default=3, verbose_name='Apprentissage (1-5)')),
                ('activities', models.TextField(blank=True, verbose_name='Activités du jour')),
                ('incidents', models.TextField(blank=True, verbose_name='Incidents / remarques')),
                ('educator_note', models.TextField(blank=True, verbose_name="Note de l'éducateur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='children.child', verbose_name='Enfant')),
                ('educator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL, verbose_name='Éducateur')),
            ],
            options={
                'verbose_name': 'Évaluation quotidienne',
                'verbose_name_plural': 'Évaluations quotidiennes',
                'ordering': ('-date',),
                'unique_together': {('child', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Début de semaine')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé de la semaine')),
                ('progress_score', models.PositiveSmallIntegerField(default=5, verbose_name='Progrès global (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='children.child', verbose_name='Enfant')),
            ],
            options={
                'verbose_name': 'Rapport hebdomadaire',
                'verbose_name_plural': 'Rapports hebdomadaires',
                'ordering': ('-week_start',),
                'unique_together': {('child', 'week_start')},
            },
        ),
    ]
