# Generated by Django 6.0.4 on 2026-05-02 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la crèche')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=120, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='France', max_length=80, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacité')),
                ('age_min_months', models.PositiveIntegerField(default=3, verbose_name='Âge minimum (mois)')),
                ('age_max_months', models.PositiveIntegerField(default=72, verbose_name='Âge maximum (mois)')),
                ('opening_hours', models.CharField(blank=True, max_length=120, verbose_name="Horaires d'ouverture")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='nurseries/', verbose_name='Image de couverture')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='nurseries/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_nurseries', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Crèche',
                'verbose_name_plural': 'Crèches',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NurseryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Service')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='Icône')),
                ('nursery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='nurseries.nursery', verbose_name='Crèche')),
            ],
            options={
                'verbose_name': 'Service de crèche',
                'verbose_name_plural': 'Services de crèche',
            },
        ),
    ]
